package com.example.deanguo.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PREPARE_INFO.
 */
public class PrepareInfo {

    private Long id;
    /** Not-null value. */
    private String route;
    /** Not-null value. */
    private String travel_type;
    private String route_overview;
    private String budget;
    private String medicine;
    private String equip;
    private String equip_clothing;
    private String outdoor_equip;
    private String credential;
    private String personal;
    private String other;

    public PrepareInfo() {
    }

    public PrepareInfo(Long id) {
        this.id = id;
    }

    public PrepareInfo(Long id, String route, String travel_type, String route_overview, String budget, String medicine, String equip, String equip_clothing, String outdoor_equip, String credential, String personal, String other) {
        this.id = id;
        this.route = route;
        this.travel_type = travel_type;
        this.route_overview = route_overview;
        this.budget = budget;
        this.medicine = medicine;
        this.equip = equip;
        this.equip_clothing = equip_clothing;
        this.outdoor_equip = outdoor_equip;
        this.credential = credential;
        this.personal = personal;
        this.other = other;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getRoute() {
        return route;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRoute(String route) {
        this.route = route;
    }

    /** Not-null value. */
    public String getTravel_type() {
        return travel_type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTravel_type(String travel_type) {
        this.travel_type = travel_type;
    }

    public String getRoute_overview() {
        return route_overview;
    }

    public void setRoute_overview(String route_overview) {
        this.route_overview = route_overview;
    }

    public String getBudget() {
        return budget;
    }

    public void setBudget(String budget) {
        this.budget = budget;
    }

    public String getMedicine() {
        return medicine;
    }

    public void setMedicine(String medicine) {
        this.medicine = medicine;
    }

    public String getEquip() {
        return equip;
    }

    public void setEquip(String equip) {
        this.equip = equip;
    }

    public String getEquip_clothing() {
        return equip_clothing;
    }

    public void setEquip_clothing(String equip_clothing) {
        this.equip_clothing = equip_clothing;
    }

    public String getOutdoor_equip() {
        return outdoor_equip;
    }

    public void setOutdoor_equip(String outdoor_equip) {
        this.outdoor_equip = outdoor_equip;
    }

    public String getCredential() {
        return credential;
    }

    public void setCredential(String credential) {
        this.credential = credential;
    }

    public String getPersonal() {
        return personal;
    }

    public void setPersonal(String personal) {
        this.personal = personal;
    }

    public String getOther() {
        return other;
    }

    public void setOther(String other) {
        this.other = other;
    }

}
