package com.daen.google.module;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.Comparator;

/**
 * Entity mapped to table GEOCODE.
 */
public class Geocode {

    private Long id;
    /**
     * Not-null value.
     */
    private String name;
    private double elevation;
    private double mileage;
    private double milestone;
    private double distance;
    private double latitude;
    private double longitude;
    private String road;


    public String getRoute() {
        return route;
    }

    public void setRoute(String route) {
        this.route = route;
    }

    public double getF_distance() {
        return f_distance;
    }

    public void setF_distance(double f_distance) {
        this.f_distance = f_distance;
    }

    public double getR_distance() {
        return r_distance;
    }

    public void setR_distance(double r_distance) {
        this.r_distance = r_distance;
    }

    public String getF_detail() {
        return f_detail;
    }

    public void setF_detail(String f_detail) {
        this.f_detail = f_detail;
    }

    public String getR_detail() {
        return r_detail;
    }

    public void setR_detail(String r_detail) {
        this.r_detail = r_detail;
    }

    public String getE_detail() {
        return e_detail;
    }

    public void setE_detail(String e_detail) {
        this.e_detail = e_detail;
    }

    public String getF_distance_point() {
        return f_distance_point;
    }

    public void setF_distance_point(String f_distance_point) {
        this.f_distance_point = f_distance_point;
    }

    public String getR_distance_point() {
        return r_distance_point;
    }

    public void setR_distance_point(String r_distance_point) {
        this.r_distance_point = r_distance_point;
    }

    public String getAround_type() {
        return around_type;
    }

    public void setAround_type(String around_type) {
        this.around_type = around_type;
    }

    private String route;
    private double f_distance;
    private double r_distance;
    private String f_detail;
    private String r_detail;
    private String e_detail;
    private String f_distance_point;
    private String r_distance_point;
    private String around_type;

    /**
     * Not-null value.
     */
    private String address;
    /**
     * Not-null value.
     */
    private String types;

    public Geocode() {
    }

    public Geocode(Long id) {
        this.id = id;
    }

    public Geocode(String name, double mileage, String types) {
        this.name = name;
        this.mileage = mileage;
        this.types = types;
    }

    public Geocode(String name, double latitude, double longitude, double mileage, double distance, String types) {
        this.name = name;
        this.mileage = mileage;
        this.milestone = mileage;
        this.latitude = latitude;
        this.longitude = longitude;
        this.distance = distance;
        this.types = types;
    }

    public Geocode(String name, double elevation, double mileage, double latitude, double longitude, double distance, String address, String types) {
        this.name = name;
        this.elevation = elevation;
        this.mileage = mileage;
        this.milestone = mileage;
        this.latitude = latitude;
        this.longitude = longitude;
        this.distance = distance;
        this.address = address;
        this.types = types;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getName() {
        return name;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setName(String name) {
        this.name = name;
    }

    public double getElevation() {
        return elevation;
    }

    public void setElevation(double elevation) {
        this.elevation = elevation;
    }

    public double getMileage() {
        return mileage;
    }

    public void setMileage(double mileage) {
        this.mileage = mileage;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    /**
     * Not-null value.
     */
    public String getAddress() {
        return address;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Not-null value.
     */
    public String getTypes() {
        return types;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */


    public String getRoad() {
        return road;
    }

    public void setRoad(String road) {
        this.road = road;
    }

    public void setTypes(String types) {
        this.types = types;
    }

    public double getDistance() {
        return distance;
    }

    public void setDistance(double distance) {
        this.distance = distance;
    }

    public double getMilestone() {
        return milestone;
    }

    public void setMilestone(double milestone) {
        this.milestone = milestone;
    }

    public static Comparator<Geocode> MileageComparator = new Comparator<Geocode>() {
        @Override
        public int compare(Geocode g1, Geocode g2) {
            if ((float)g2.mileage > (float)g1.mileage) {
                return -1;
            } else {
                return 1;
            }
        }
    };
}
