package com.dean.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BUILDING_TYPE.
 */
public class BuildingType {

    private Long id;
    /** Not-null value. */
    private String TUNNEL;
    /** Not-null value. */
    private String VIEW;
    /** Not-null value. */
    private String TENT;
    /** Not-null value. */
    private String HOTEL;
    /** Not-null value. */
    private String STORE;
    /** Not-null value. */
    private String CHECKPOINT;
    /** Not-null value. */
    private String BRIDGE;

    public BuildingType() {
    }

    public BuildingType(Long id) {
        this.id = id;
    }

    public BuildingType(Long id, String TUNNEL, String VIEW, String TENT, String HOTEL, String STORE, String CHECKPOINT, String BRIDGE) {
        this.id = id;
        this.TUNNEL = TUNNEL;
        this.VIEW = VIEW;
        this.TENT = TENT;
        this.HOTEL = HOTEL;
        this.STORE = STORE;
        this.CHECKPOINT = CHECKPOINT;
        this.BRIDGE = BRIDGE;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTUNNEL() {
        return TUNNEL;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTUNNEL(String TUNNEL) {
        this.TUNNEL = TUNNEL;
    }

    /** Not-null value. */
    public String getVIEW() {
        return VIEW;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVIEW(String VIEW) {
        this.VIEW = VIEW;
    }

    /** Not-null value. */
    public String getTENT() {
        return TENT;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTENT(String TENT) {
        this.TENT = TENT;
    }

    /** Not-null value. */
    public String getHOTEL() {
        return HOTEL;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHOTEL(String HOTEL) {
        this.HOTEL = HOTEL;
    }

    /** Not-null value. */
    public String getSTORE() {
        return STORE;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSTORE(String STORE) {
        this.STORE = STORE;
    }

    /** Not-null value. */
    public String getCHECKPOINT() {
        return CHECKPOINT;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCHECKPOINT(String CHECKPOINT) {
        this.CHECKPOINT = CHECKPOINT;
    }

    /** Not-null value. */
    public String getBRIDGE() {
        return BRIDGE;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBRIDGE(String BRIDGE) {
        this.BRIDGE = BRIDGE;
    }

}
