package com.dean.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dean.greendao.Geocode;
import com.dean.greendao.Plan;
import com.dean.greendao.Route;

import com.dean.greendao.GeocodeDao;
import com.dean.greendao.PlanDao;
import com.dean.greendao.RouteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig geocodeDaoConfig;
    private final DaoConfig planDaoConfig;
    private final DaoConfig routeDaoConfig;

    private final GeocodeDao geocodeDao;
    private final PlanDao planDao;
    private final RouteDao routeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        geocodeDaoConfig = daoConfigMap.get(GeocodeDao.class).clone();
        geocodeDaoConfig.initIdentityScope(type);

        planDaoConfig = daoConfigMap.get(PlanDao.class).clone();
        planDaoConfig.initIdentityScope(type);

        routeDaoConfig = daoConfigMap.get(RouteDao.class).clone();
        routeDaoConfig.initIdentityScope(type);

        geocodeDao = new GeocodeDao(geocodeDaoConfig, this);
        planDao = new PlanDao(planDaoConfig, this);
        routeDao = new RouteDao(routeDaoConfig, this);

        registerDao(Geocode.class, geocodeDao);
        registerDao(Plan.class, planDao);
        registerDao(Route.class, routeDao);
    }
    
    public void clear() {
        geocodeDaoConfig.getIdentityScope().clear();
        planDaoConfig.getIdentityScope().clear();
        routeDaoConfig.getIdentityScope().clear();
    }

    public GeocodeDao getGeocodeDao() {
        return geocodeDao;
    }

    public PlanDao getPlanDao() {
        return planDao;
    }

    public RouteDao getRouteDao() {
        return routeDao;
    }

}
