package com.dean.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dean.greendao.Geocode;
import com.dean.greendao.Routes;
import com.dean.greendao.ZoneType;
import com.dean.greendao.BuildingType;

import com.dean.greendao.GeocodeDao;
import com.dean.greendao.RoutesDao;
import com.dean.greendao.ZoneTypeDao;
import com.dean.greendao.BuildingTypeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig geocodeDaoConfig;
    private final DaoConfig routesDaoConfig;
    private final DaoConfig zoneTypeDaoConfig;
    private final DaoConfig buildingTypeDaoConfig;

    private final GeocodeDao geocodeDao;
    private final RoutesDao routesDao;
    private final ZoneTypeDao zoneTypeDao;
    private final BuildingTypeDao buildingTypeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        geocodeDaoConfig = daoConfigMap.get(GeocodeDao.class).clone();
        geocodeDaoConfig.initIdentityScope(type);

        routesDaoConfig = daoConfigMap.get(RoutesDao.class).clone();
        routesDaoConfig.initIdentityScope(type);

        zoneTypeDaoConfig = daoConfigMap.get(ZoneTypeDao.class).clone();
        zoneTypeDaoConfig.initIdentityScope(type);

        buildingTypeDaoConfig = daoConfigMap.get(BuildingTypeDao.class).clone();
        buildingTypeDaoConfig.initIdentityScope(type);

        geocodeDao = new GeocodeDao(geocodeDaoConfig, this);
        routesDao = new RoutesDao(routesDaoConfig, this);
        zoneTypeDao = new ZoneTypeDao(zoneTypeDaoConfig, this);
        buildingTypeDao = new BuildingTypeDao(buildingTypeDaoConfig, this);

        registerDao(Geocode.class, geocodeDao);
        registerDao(Routes.class, routesDao);
        registerDao(ZoneType.class, zoneTypeDao);
        registerDao(BuildingType.class, buildingTypeDao);
    }
    
    public void clear() {
        geocodeDaoConfig.getIdentityScope().clear();
        routesDaoConfig.getIdentityScope().clear();
        zoneTypeDaoConfig.getIdentityScope().clear();
        buildingTypeDaoConfig.getIdentityScope().clear();
    }

    public GeocodeDao getGeocodeDao() {
        return geocodeDao;
    }

    public RoutesDao getRoutesDao() {
        return routesDao;
    }

    public ZoneTypeDao getZoneTypeDao() {
        return zoneTypeDao;
    }

    public BuildingTypeDao getBuildingTypeDao() {
        return buildingTypeDao;
    }

}
