package com.dean.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GEOCODE.
 */
public class Geocode {

    private Long id;
    /** Not-null value. */
    private String name;
    private double elevation;
    private double mileage;
    private double milestone;
    private double distance;
    private double latitude;
    private double longitude;
    /** Not-null value. */
    private String address;
    /** Not-null value. */
    private String types;
    private String road;

    public Geocode() {
    }

    public Geocode(Long id) {
        this.id = id;
    }

    public Geocode(Long id, String name, double elevation, double mileage, double milestone, double distance, double latitude, double longitude, String address, String types, String road) {
        this.id = id;
        this.name = name;
        this.elevation = elevation;
        this.mileage = mileage;
        this.milestone = milestone;
        this.distance = distance;
        this.latitude = latitude;
        this.longitude = longitude;
        this.address = address;
        this.types = types;
        this.road = road;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public double getElevation() {
        return elevation;
    }

    public void setElevation(double elevation) {
        this.elevation = elevation;
    }

    public double getMileage() {
        return mileage;
    }

    public void setMileage(double mileage) {
        this.mileage = mileage;
    }

    public double getMilestone() {
        return milestone;
    }

    public void setMilestone(double milestone) {
        this.milestone = milestone;
    }

    public double getDistance() {
        return distance;
    }

    public void setDistance(double distance) {
        this.distance = distance;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    /** Not-null value. */
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(String address) {
        this.address = address;
    }

    /** Not-null value. */
    public String getTypes() {
        return types;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTypes(String types) {
        this.types = types;
    }

    public String getRoad() {
        return road;
    }

    public void setRoad(String road) {
        this.road = road;
    }

}
