package com.dean.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GEOCODE.
 */
public class Geocode {

    private Long id;
    /** Not-null value. */
    private String route;
    /** Not-null value. */
    private String name;
    private double elevation;
    private double f_distance;
    private double r_distance;
    private double latitude;
    private double longitude;
    /** Not-null value. */
    private String address;
    /** Not-null value. */
    private String types;
    private String milestone;
    private String road;
    private String f_detail;
    private String r_detail;
    private String e_detail;
    private String f_distance_point;
    private String r_distance_point;
    private String around_type;

    public Geocode() {
    }

    public Geocode(Long id) {
        this.id = id;
    }

    public Geocode(Long id, String route, String name, double elevation, double f_distance, double r_distance, double latitude, double longitude, String address, String types, String milestone, String road, String f_detail, String r_detail, String e_detail, String f_distance_point, String r_distance_point, String around_type) {
        this.id = id;
        this.route = route;
        this.name = name;
        this.elevation = elevation;
        this.f_distance = f_distance;
        this.r_distance = r_distance;
        this.latitude = latitude;
        this.longitude = longitude;
        this.address = address;
        this.types = types;
        this.milestone = milestone;
        this.road = road;
        this.f_detail = f_detail;
        this.r_detail = r_detail;
        this.e_detail = e_detail;
        this.f_distance_point = f_distance_point;
        this.r_distance_point = r_distance_point;
        this.around_type = around_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getRoute() {
        return route;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRoute(String route) {
        this.route = route;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public double getElevation() {
        return elevation;
    }

    public void setElevation(double elevation) {
        this.elevation = elevation;
    }

    public double getF_distance() {
        return f_distance;
    }

    public void setF_distance(double f_distance) {
        this.f_distance = f_distance;
    }

    public double getR_distance() {
        return r_distance;
    }

    public void setR_distance(double r_distance) {
        this.r_distance = r_distance;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    /** Not-null value. */
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(String address) {
        this.address = address;
    }

    /** Not-null value. */
    public String getTypes() {
        return types;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTypes(String types) {
        this.types = types;
    }

    public String getMilestone() {
        return milestone;
    }

    public void setMilestone(String milestone) {
        this.milestone = milestone;
    }

    public String getRoad() {
        return road;
    }

    public void setRoad(String road) {
        this.road = road;
    }

    public String getF_detail() {
        return f_detail;
    }

    public void setF_detail(String f_detail) {
        this.f_detail = f_detail;
    }

    public String getR_detail() {
        return r_detail;
    }

    public void setR_detail(String r_detail) {
        this.r_detail = r_detail;
    }

    public String getE_detail() {
        return e_detail;
    }

    public void setE_detail(String e_detail) {
        this.e_detail = e_detail;
    }

    public String getF_distance_point() {
        return f_distance_point;
    }

    public void setF_distance_point(String f_distance_point) {
        this.f_distance_point = f_distance_point;
    }

    public String getR_distance_point() {
        return r_distance_point;
    }

    public void setR_distance_point(String r_distance_point) {
        this.r_distance_point = r_distance_point;
    }

    public String getAround_type() {
        return around_type;
    }

    public void setAround_type(String around_type) {
        this.around_type = around_type;
    }

}
