package com.dean.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HOTEL.
 */
public class Hotel {

    private Long id;
    /** Not-null value. */
    private String route;
    /** Not-null value. */
    private String place_name;
    /** Not-null value. */
    private String hotel_name;
    private String hotel_address;
    private String hotel_tel;
    private String hotel_detail;
    private String hotel_pic;
    private String hotel_type;

    public Hotel() {
    }

    public Hotel(Long id) {
        this.id = id;
    }

    public Hotel(Long id, String route, String place_name, String hotel_name, String hotel_address, String hotel_tel, String hotel_detail, String hotel_pic, String hotel_type) {
        this.id = id;
        this.route = route;
        this.place_name = place_name;
        this.hotel_name = hotel_name;
        this.hotel_address = hotel_address;
        this.hotel_tel = hotel_tel;
        this.hotel_detail = hotel_detail;
        this.hotel_pic = hotel_pic;
        this.hotel_type = hotel_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getRoute() {
        return route;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRoute(String route) {
        this.route = route;
    }

    /** Not-null value. */
    public String getPlace_name() {
        return place_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlace_name(String place_name) {
        this.place_name = place_name;
    }

    /** Not-null value. */
    public String getHotel_name() {
        return hotel_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHotel_name(String hotel_name) {
        this.hotel_name = hotel_name;
    }

    public String getHotel_address() {
        return hotel_address;
    }

    public void setHotel_address(String hotel_address) {
        this.hotel_address = hotel_address;
    }

    public String getHotel_tel() {
        return hotel_tel;
    }

    public void setHotel_tel(String hotel_tel) {
        this.hotel_tel = hotel_tel;
    }

    public String getHotel_detail() {
        return hotel_detail;
    }

    public void setHotel_detail(String hotel_detail) {
        this.hotel_detail = hotel_detail;
    }

    public String getHotel_pic() {
        return hotel_pic;
    }

    public void setHotel_pic(String hotel_pic) {
        this.hotel_pic = hotel_pic;
    }

    public String getHotel_type() {
        return hotel_type;
    }

    public void setHotel_type(String hotel_type) {
        this.hotel_type = hotel_type;
    }

}
