package com.dean.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOCATION.
 */
public class Location {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String height;
    /** Not-null value. */
    private String mileage;

    public Location() {
    }

    public Location(Long id) {
        this.id = id;
    }

    public Location(Long id, String name, String height, String mileage) {
        this.id = id;
        this.name = name;
        this.height = height;
        this.mileage = mileage;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getHeight() {
        return height;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHeight(String height) {
        this.height = height;
    }

    /** Not-null value. */
    public String getMileage() {
        return mileage;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMileage(String mileage) {
        this.mileage = mileage;
    }

}
