package com.dean.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PREPARE_INFO.
 */
public class PrepareInfo {

    private Long id;
    /** Not-null value. */
    private String route;
    /** Not-null value. */
    private String travel_type;
    private String budget;
    private String medicine;
    private String equip;
    private String clothing;
    private String outdoor;
    private String credential;
    private String personal;
    private String other;
    private String attention;

    public PrepareInfo() {
    }

    public PrepareInfo(Long id) {
        this.id = id;
    }

    public PrepareInfo(Long id, String route, String travel_type, String budget, String medicine, String equip, String clothing, String outdoor, String credential, String personal, String other, String attention) {
        this.id = id;
        this.route = route;
        this.travel_type = travel_type;
        this.budget = budget;
        this.medicine = medicine;
        this.equip = equip;
        this.clothing = clothing;
        this.outdoor = outdoor;
        this.credential = credential;
        this.personal = personal;
        this.other = other;
        this.attention = attention;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getRoute() {
        return route;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRoute(String route) {
        this.route = route;
    }

    /** Not-null value. */
    public String getTravel_type() {
        return travel_type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTravel_type(String travel_type) {
        this.travel_type = travel_type;
    }

    public String getBudget() {
        return budget;
    }

    public void setBudget(String budget) {
        this.budget = budget;
    }

    public String getMedicine() {
        return medicine;
    }

    public void setMedicine(String medicine) {
        this.medicine = medicine;
    }

    public String getEquip() {
        return equip;
    }

    public void setEquip(String equip) {
        this.equip = equip;
    }

    public String getClothing() {
        return clothing;
    }

    public void setClothing(String clothing) {
        this.clothing = clothing;
    }

    public String getOutdoor() {
        return outdoor;
    }

    public void setOutdoor(String outdoor) {
        this.outdoor = outdoor;
    }

    public String getCredential() {
        return credential;
    }

    public void setCredential(String credential) {
        this.credential = credential;
    }

    public String getPersonal() {
        return personal;
    }

    public void setPersonal(String personal) {
        this.personal = personal;
    }

    public String getOther() {
        return other;
    }

    public void setOther(String other) {
        this.other = other;
    }

    public String getAttention() {
        return attention;
    }

    public void setAttention(String attention) {
        this.attention = attention;
    }

}
