package com.dean.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PREPARE_INFO.
 */
public class PrepareInfo {

    private Long id;
    /** Not-null value. */
    private String route;
    private String route_detail;
    private String budget;
    private String medicine;
    private String equip_bike;
    private String equip_hike;
    private String equip_moto;
    private String equip_car;
    private String equip_clothing;
    private String outdoor_equip;
    private String credential;
    private String personal;
    private String other;

    public PrepareInfo() {
    }

    public PrepareInfo(Long id) {
        this.id = id;
    }

    public PrepareInfo(Long id, String route, String route_detail, String budget, String medicine, String equip_bike, String equip_hike, String equip_moto, String equip_car, String equip_clothing, String outdoor_equip, String credential, String personal, String other) {
        this.id = id;
        this.route = route;
        this.route_detail = route_detail;
        this.budget = budget;
        this.medicine = medicine;
        this.equip_bike = equip_bike;
        this.equip_hike = equip_hike;
        this.equip_moto = equip_moto;
        this.equip_car = equip_car;
        this.equip_clothing = equip_clothing;
        this.outdoor_equip = outdoor_equip;
        this.credential = credential;
        this.personal = personal;
        this.other = other;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getRoute() {
        return route;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRoute(String route) {
        this.route = route;
    }

    public String getRoute_detail() {
        return route_detail;
    }

    public void setRoute_detail(String route_detail) {
        this.route_detail = route_detail;
    }

    public String getBudget() {
        return budget;
    }

    public void setBudget(String budget) {
        this.budget = budget;
    }

    public String getMedicine() {
        return medicine;
    }

    public void setMedicine(String medicine) {
        this.medicine = medicine;
    }

    public String getEquip_bike() {
        return equip_bike;
    }

    public void setEquip_bike(String equip_bike) {
        this.equip_bike = equip_bike;
    }

    public String getEquip_hike() {
        return equip_hike;
    }

    public void setEquip_hike(String equip_hike) {
        this.equip_hike = equip_hike;
    }

    public String getEquip_moto() {
        return equip_moto;
    }

    public void setEquip_moto(String equip_moto) {
        this.equip_moto = equip_moto;
    }

    public String getEquip_car() {
        return equip_car;
    }

    public void setEquip_car(String equip_car) {
        this.equip_car = equip_car;
    }

    public String getEquip_clothing() {
        return equip_clothing;
    }

    public void setEquip_clothing(String equip_clothing) {
        this.equip_clothing = equip_clothing;
    }

    public String getOutdoor_equip() {
        return outdoor_equip;
    }

    public void setOutdoor_equip(String outdoor_equip) {
        this.outdoor_equip = outdoor_equip;
    }

    public String getCredential() {
        return credential;
    }

    public void setCredential(String credential) {
        this.credential = credential;
    }

    public String getPersonal() {
        return personal;
    }

    public void setPersonal(String personal) {
        this.personal = personal;
    }

    public String getOther() {
        return other;
    }

    public void setOther(String other) {
        this.other = other;
    }

}
