package com.dean.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ROUTE_PLAN.
 */
public class RoutePlan {

    private Long id;
    /** Not-null value. */
    private String route;
    /** Not-null value. */
    private String fr;
    /** Not-null value. */
    private String type;
    /** Not-null value. */
    private String plan_name;
    /** Not-null value. */
    private String plan_days;
    /** Not-null value. */
    private String describe;

    public RoutePlan() {
    }

    public RoutePlan(Long id) {
        this.id = id;
    }

    public RoutePlan(Long id, String route, String fr, String type, String plan_name, String plan_days, String describe) {
        this.id = id;
        this.route = route;
        this.fr = fr;
        this.type = type;
        this.plan_name = plan_name;
        this.plan_days = plan_days;
        this.describe = describe;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getRoute() {
        return route;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRoute(String route) {
        this.route = route;
    }

    /** Not-null value. */
    public String getFr() {
        return fr;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFr(String fr) {
        this.fr = fr;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getPlan_name() {
        return plan_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlan_name(String plan_name) {
        this.plan_name = plan_name;
    }

    /** Not-null value. */
    public String getPlan_days() {
        return plan_days;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlan_days(String plan_days) {
        this.plan_days = plan_days;
    }

    /** Not-null value. */
    public String getDescribe() {
        return describe;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescribe(String describe) {
        this.describe = describe;
    }

}
