package com.dean.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table SCENIC.
 */
public class Scenic implements Serializable{

    private Long id;
    /** Not-null value. */
    private String route;
    /** Not-null value. */
    private String scenic_name;
    private String scenic_f_belong;
    private String scenic_r_belong;
    private String scenic_overview;
    private String scenic_detail;
    private String scenic_address;
    private String scenic_f_traffic;
    private String scenic_r_traffic;
    private String scenic_opentime;
    private String scenic_pic;

    public Scenic() {
    }

    public Scenic(Long id) {
        this.id = id;
    }

    public Scenic(Long id, String route, String scenic_name, String scenic_f_belong, String scenic_r_belong, String scenic_overview, String scenic_detail, String scenic_address, String scenic_f_traffic, String scenic_r_traffic, String scenic_opentime, String scenic_pic) {
        this.id = id;
        this.route = route;
        this.scenic_name = scenic_name;
        this.scenic_f_belong = scenic_f_belong;
        this.scenic_r_belong = scenic_r_belong;
        this.scenic_overview = scenic_overview;
        this.scenic_detail = scenic_detail;
        this.scenic_address = scenic_address;
        this.scenic_f_traffic = scenic_f_traffic;
        this.scenic_r_traffic = scenic_r_traffic;
        this.scenic_opentime = scenic_opentime;
        this.scenic_pic = scenic_pic;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getRoute() {
        return route;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRoute(String route) {
        this.route = route;
    }

    /** Not-null value. */
    public String getScenic_name() {
        return scenic_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setScenic_name(String scenic_name) {
        this.scenic_name = scenic_name;
    }

    public String getScenic_f_belong() {
        return scenic_f_belong;
    }

    public void setScenic_f_belong(String scenic_f_belong) {
        this.scenic_f_belong = scenic_f_belong;
    }

    public String getScenic_r_belong() {
        return scenic_r_belong;
    }

    public void setScenic_r_belong(String scenic_r_belong) {
        this.scenic_r_belong = scenic_r_belong;
    }

    public String getScenic_overview() {
        return scenic_overview;
    }

    public void setScenic_overview(String scenic_overview) {
        this.scenic_overview = scenic_overview;
    }

    public String getScenic_detail() {
        return scenic_detail;
    }

    public void setScenic_detail(String scenic_detail) {
        this.scenic_detail = scenic_detail;
    }

    public String getScenic_address() {
        return scenic_address;
    }

    public void setScenic_address(String scenic_address) {
        this.scenic_address = scenic_address;
    }

    public String getScenic_f_traffic() {
        return scenic_f_traffic;
    }

    public void setScenic_f_traffic(String scenic_f_traffic) {
        this.scenic_f_traffic = scenic_f_traffic;
    }

    public String getScenic_r_traffic() {
        return scenic_r_traffic;
    }

    public void setScenic_r_traffic(String scenic_r_traffic) {
        this.scenic_r_traffic = scenic_r_traffic;
    }

    public String getScenic_opentime() {
        return scenic_opentime;
    }

    public void setScenic_opentime(String scenic_opentime) {
        this.scenic_opentime = scenic_opentime;
    }

    public String getScenic_pic() {
        return scenic_pic;
    }

    public void setScenic_pic(String scenic_pic) {
        this.scenic_pic = scenic_pic;
    }

}
