package com.dean.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.dean.greendao.Scenic;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SCENIC.
*/
public class ScenicDao extends AbstractDao<Scenic, Long> {

    public static final String TABLENAME = "SCENIC";

    /**
     * Properties of entity Scenic.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Route = new Property(1, String.class, "route", false, "ROUTE");
        public final static Property Scenic_name = new Property(2, String.class, "scenic_name", false, "SCENIC_NAME");
        public final static Property Scenic_overview = new Property(3, String.class, "scenic_overview", false, "SCENIC_OVERVIEW");
        public final static Property Scenic_detail = new Property(4, String.class, "scenic_detail", false, "SCENIC_DETAIL");
        public final static Property Scenic_pic = new Property(5, String.class, "scenic_pic", false, "SCENIC_PIC");
    };


    public ScenicDao(DaoConfig config) {
        super(config);
    }
    
    public ScenicDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SCENIC' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ROUTE' TEXT NOT NULL ," + // 1: route
                "'SCENIC_NAME' TEXT NOT NULL ," + // 2: scenic_name
                "'SCENIC_OVERVIEW' TEXT," + // 3: scenic_overview
                "'SCENIC_DETAIL' TEXT," + // 4: scenic_detail
                "'SCENIC_PIC' TEXT);"); // 5: scenic_pic
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SCENIC'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Scenic entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getRoute());
        stmt.bindString(3, entity.getScenic_name());
 
        String scenic_overview = entity.getScenic_overview();
        if (scenic_overview != null) {
            stmt.bindString(4, scenic_overview);
        }
 
        String scenic_detail = entity.getScenic_detail();
        if (scenic_detail != null) {
            stmt.bindString(5, scenic_detail);
        }
 
        String scenic_pic = entity.getScenic_pic();
        if (scenic_pic != null) {
            stmt.bindString(6, scenic_pic);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Scenic readEntity(Cursor cursor, int offset) {
        Scenic entity = new Scenic( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // route
            cursor.getString(offset + 2), // scenic_name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // scenic_overview
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // scenic_detail
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // scenic_pic
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Scenic entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRoute(cursor.getString(offset + 1));
        entity.setScenic_name(cursor.getString(offset + 2));
        entity.setScenic_overview(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setScenic_detail(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setScenic_pic(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Scenic entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Scenic entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
