package com.dean.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ZONE_TYPE.
 */
public class ZoneType {

    private Long id;
    /** Not-null value. */
    private String CITY;
    /** Not-null value. */
    private String COUNTY;
    /** Not-null value. */
    private String TOWN;
    /** Not-null value. */
    private String VILLAGE;
    /** Not-null value. */
    private String DAOBAN;
    /** Not-null value. */
    private String MOUNTAIN;
    /** Not-null value. */
    private String SCENICSPOT;
    /** Not-null value. */
    private String BUILDING;
    /** Not-null value. */
    private String OTHERS;

    public ZoneType() {
    }

    public ZoneType(Long id) {
        this.id = id;
    }

    public ZoneType(Long id, String CITY, String COUNTY, String TOWN, String VILLAGE, String DAOBAN, String MOUNTAIN, String SCENICSPOT, String BUILDING, String OTHERS) {
        this.id = id;
        this.CITY = CITY;
        this.COUNTY = COUNTY;
        this.TOWN = TOWN;
        this.VILLAGE = VILLAGE;
        this.DAOBAN = DAOBAN;
        this.MOUNTAIN = MOUNTAIN;
        this.SCENICSPOT = SCENICSPOT;
        this.BUILDING = BUILDING;
        this.OTHERS = OTHERS;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCITY() {
        return CITY;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCITY(String CITY) {
        this.CITY = CITY;
    }

    /** Not-null value. */
    public String getCOUNTY() {
        return COUNTY;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCOUNTY(String COUNTY) {
        this.COUNTY = COUNTY;
    }

    /** Not-null value. */
    public String getTOWN() {
        return TOWN;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTOWN(String TOWN) {
        this.TOWN = TOWN;
    }

    /** Not-null value. */
    public String getVILLAGE() {
        return VILLAGE;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVILLAGE(String VILLAGE) {
        this.VILLAGE = VILLAGE;
    }

    /** Not-null value. */
    public String getDAOBAN() {
        return DAOBAN;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDAOBAN(String DAOBAN) {
        this.DAOBAN = DAOBAN;
    }

    /** Not-null value. */
    public String getMOUNTAIN() {
        return MOUNTAIN;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMOUNTAIN(String MOUNTAIN) {
        this.MOUNTAIN = MOUNTAIN;
    }

    /** Not-null value. */
    public String getSCENICSPOT() {
        return SCENICSPOT;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSCENICSPOT(String SCENICSPOT) {
        this.SCENICSPOT = SCENICSPOT;
    }

    /** Not-null value. */
    public String getBUILDING() {
        return BUILDING;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBUILDING(String BUILDING) {
        this.BUILDING = BUILDING;
    }

    /** Not-null value. */
    public String getOTHERS() {
        return OTHERS;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOTHERS(String OTHERS) {
        this.OTHERS = OTHERS;
    }

}
